/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const SpeedTestResult = IDL.Record({
  'ping' : IDL.Nat,
  'uploadSpeed' : IDL.Float64,
  'timestamp' : Time,
  'downloadSpeed' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addResult' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Nat], [], []),
  'getResults' : IDL.Func([], [IDL.Vec(SpeedTestResult)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const SpeedTestResult = IDL.Record({
    'ping' : IDL.Nat,
    'uploadSpeed' : IDL.Float64,
    'timestamp' : Time,
    'downloadSpeed' : IDL.Float64,
  });
  
  return IDL.Service({
    'addResult' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Nat], [], []),
    'getResults' : IDL.Func([], [IDL.Vec(SpeedTestResult)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };